### ISSUE TITLE
Doc edit request - compositeAbundance (2.1.0)

### ISSUE THREAD

**Issue by davidlbean** [belbio/bel_lang_ws#10]
function parameters illustrated as:  
```
compositeAbundance(a|act|p|g|m|r|complex|pop(), NSArg) 
```

function explanation, however, says the last argument is:  
```
2. Zero or more namespace arguments of following type(s): Complex
```

Is the last argument an NSArg or a Complex?

**Comment by wshayes** [comment]
Complexes can be NSArgs or complex() functions. They are unusual in that regard.  e.g. SCOMP:"AP-1 Complex".  

What I was trying to get across is that composite() can have the functional members and/or a Complex NS:Value.  

Please feel free to submit a pull request to make this easier to understand. I appreciate your digging into this.

**Comment by davidlbean** [comment]
@wshayes Hi William -- I'm poking around the repo and I don't see the content that drives the pages...maybe getting pulled from another source dynamically?  Was going to update the textual description in a PR but would it be better just to submit a proposed change as comment of a PR (instead of as a code change)?  Whatever works best for you...  thx.

**Comment by wshayes** [comment]
The following is accurate - what would you suggest to make it easier to understand?  I can add more examples and more descriptions in the language documents. Are you referring to this help in the Knowledge (Nanopub) editor or in the https://language.bel.bio website?  The lines 1 and 2 are generated programmatically based on the function signatures for the composite function found here: https://github.com/belbio/bel_specifications/blob/master/specifications/bel_v2_1_0.yaml#L363-L386 

BTW - my email is whayes at biodati dot com - happy to do a zoom conference to sort this out faster.

### compositeAbundance(a|act|p|g|m|r|complex|pop(), NSArg)
1. Zero or more of each function(s): abundance, activity, proteinAbundance, geneAbundance, microRNAAbundance, rnaAbundance, complexAbundance, populationAbundance
2. Zero or more namespace arguments of following type(s): Complex

https://language.bel.bio/language/reference/2.1.0/functions/compositeabundance/

**Comment by davidlbean** [comment]
William - ah...I see.  You're right, it's ok.  My confusion came from the similarity between an NSArg Complex and a ComplexAbundance function which references an NSArg Complex itself.  That was my bad...after working through a bunch of the other functions, I see now that an NSArg typically has a named type to it.  Sorry to bug you as I climbed the learning curve!

**Comment by wshayes** [comment]
No worries at all - we keep trying to make this as simple as possible, and we value feedback to further the project.
