### ISSUE TITLE
bel.bio is down

### ISSUE THREAD

**Issue by brucetony** [belbio/bel_lang_ws#16]
There is an issue with the website currently and it is not accessible. I attempted to run a local version, but it appears it is dependent on http://bel.bio in order to run according to your README:

> Also note that all of the pages under content/language/reference is created by ./bin/update_refs.py based on content pulled from http://resources.bel.bio/?prefix=specifications/.

It may be useful to move those resources to an external server to avoid this cyclical dependency, as I believe it is why the website is currently down.

Thanks for the help!

**Comment by wshayes** [comment]
Thanks for letting me know - I'll work on it this evening.

**Comment by wshayes** [comment]
@brucetony bel.bio and language.bel.bio and resources.bel.bio should be up again. There were some bumps moving bel.bio when Biodati shut down. Thanks for letting me know. Please let me know if there is anything else that you are using that is broken. The demo/community BEL API is not possible to spin up as I can't justify that out of my personal finances - happy to help spin it up if someone has a server to spare.

I do need to move the specs into the language.bel.bio website to make it all easier to work with. If you are interested in pitching in, I'd be happy for the help. Unfortunately, my day job has been taking up my weeks, weekends and holidays lately.

**Comment by brucetony** [comment]
@wshayes Thank you so much for getting the website back online. I would be happy to help where I can, perhaps we can have a short call in the near future to discuss what needs to be done and how to coordinate. Feel free to contact me at my email in my profile here on GitHub.
